Simulation of a Quantum Teleportation Circuit

Let's start by defining some gates and states using numpy arrays

In [10]:
import numpy as np

X = np.array([[0,1],[1,0]])
Y = np.array([[0, -1j],[1j, 0]])
Z = np.array([[1,0],[0,-1]])

print(f'The Pauli matrices are:\nX={X}\nY={Y}\nZ={Z}')


The Pauli matrices are:
X=[[0 1]
 [1 0]]
Y=[[ 0.+0.j -0.-1.j]
 [ 0.+1.j  0.+0.j]]
Z=[[ 1  0]
 [ 0 -1]]


In [13]:
state_0 = np.array([1,0]).reshape((2,1))
state_1 = np.array([0,1]).reshape((2,1))
state_plus = np.array([1/np.sqrt(2), 1/np.sqrt(2)]).reshape((2,1))
state_T = np.array([1/np.sqrt(2), np.exp(1j*np.pi/4)/np.sqrt(2)]).reshape((2,1))

print(f'The states are:\n|0>={state_0}\n|1>={state_1}\n|+>={state_plus}\n|T>={state_T}')

The states are:
|0>=[[1]
 [0]]
|1>=[[0]
 [1]]
|+>=[[0.70710678]
 [0.70710678]]
|T>=[[0.70710678+0.j ]
 [0.5       +0.5j]]


Now, let's apply the gates to these states to check they return what's expected

In [15]:
# apply the gates to the states
print(f'X|0>={X @ state_0}\nY|1>={Y @ state_1}\nZ|+>={Z @ state_plus}\nY|T>={Y @ state_T}')

X|0>=[[0]
 [1]]
Y|1>=[[0.-1.j]
 [0.+0.j]]
Z|+>=[[ 0.70710678]
 [-0.70710678]]
Y|T>=[[0.5-0.5j       ]
 [0. +0.70710678j]]


Apply CNOT and CZ gates to |00>, |+0>, |++>

In [ ]:
CNOT = np.array([[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]])
CZ = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,-1]])

print(f'Gates are defined as:\
      \nCNOT={CNOT}\
      \nCZ={CZ}\n')

# apply CNOT and CZ gates to |00>, |+0>, |++>

# Numpy function np.kron computes the Kronecker product (a.k.a. tensor product) of two matrices or vectors.

state_00 = np.kron(state_0, state_0)
state_11 = np.kron(state_1, state_1)
state_plus_0 = np.kron(state_plus, state_0)
state_plus_plus = np.kron(state_plus, state_plus)

print(f'States are defined as:\
      \n|00>={state_00}\
      \n|11>={state_11}\
      \n|+0>={state_plus_0}\
      \n|++>={state_plus_plus}\n')

Gates are defined as:      
cnot=[[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]]      
cz=[[ 1  0  0  0]
 [ 0  1  0  0]
 [ 0  0  1  0]
 [ 0  0  0 -1]]

States are defined as:      
|00>=[[1]
 [0]
 [0]
 [0]]      
|11>=[[0]
 [0]
 [0]
 [1]]      
|+0>=[[0.70710678]
 [0.        ]
 [0.70710678]
 [0.        ]]      
|++>=[[0.5]
 [0.5]
 [0.5]
 [0.5]]



In [ ]:
print('If we apply some gates to them:')
print(f'CNOT|00>={CNOT @ state_00}\
      \nCNOT|11>={CNOT @ state_11}\
      \nCNOT|+0>={CNOT @ state_plus_0}\
      \nCNOT|++>={CNOT @ state_plus_plus}')
print(f'CZ|00>={CZ @ state_00}\nCZ|+0>={CZ @ state_plus_0}\nCZ|++>={CZ @ state_plus_plus}')

If we apply some gates to them:
CNOT|00>=[[1]
 [0]
 [0]
 [0]]      
CNOT|11>=[[0]
 [0]
 [1]
 [0]]      
CNOT|+0>=[[0.70710678]
 [0.        ]
 [0.        ]
 [0.70710678]]      
CNOT|++>=[[0.5]
 [0.5]
 [0.5]
 [0.5]]
CZ|00>=[[1]
 [0]
 [0]
 [0]]
CZ|+0>=[[0.70710678]
 [0.        ]
 [0.70710678]
 [0.        ]]
CZ|++>=[[ 0.5]
 [ 0.5]
 [ 0.5]
 [-0.5]]


In [31]:
def circuit_1q(in_state: np.array, gates: list) -> np.array:
    """
    Apply a list of gates to a single qubit state.
    
    Parameters:
    in_state (np.array): Input state vector.
    gates (list): List of gate matrices to apply.
    
    Returns:
    np.array: Resulting state after applying the gates.
    """
    state = in_state
    for gate in gates:
        state = gate @ state
    return state

In [32]:
# Hadamard gate
H = 1/np.sqrt(2) * np.array([[1,1],[1,-1]])

In [ ]:
def qtel(state_in: np.array):
    # A & B share an EPR pair
    bell_state_AB = 1/np.sqrt(2) * np.array([1,0,0,1])

    state = np.kron(state_in, bell_state_AB)

    # CNOT
    state = (np.kron(CNOT, np.identity(2))) @ state

    print(state)

In [ ]:
state_in = np.array([0,1])

# A & B share an EPR pair
bell_state_AB = 1/np.sqrt(2) * np.array([1,0,0,1])  # EPR pair 1/sqrt(2) * (|00> +|11>)

state = np.kron(state_in, bell_state_AB)

print(f'Initial global state CAB:\n{state}\n')

# CNOT
state = (np.kron(CNOT, np.identity(2))) @ state

print(f'State after CNOT:\n{state}')

# Hadamard
state = (np.kron(np.kron(H,np.identity(2)), np.identity(2))) @ state

print(f'State after Hadamard on system C:\n{state}')

# Measurement A
p = np.random.uniform()
if p < 0.5:
    #apply 0
    proj = np.kron(np.identity(2), np.kron(np.array([[1,0],[0,0]]), np.identity(2)))
    
else:
    #apply 1
    proj = np.kron(np.identity(2), np.kron(np.array([[0,0],[0,1]]), np.identity(2)))

# Apply projection
state = proj @ state


Initial global state CAB:
[0.         0.         0.         0.         0.70710678 0.
 0.         0.70710678]

State after CNOT:
[0.         0.         0.         0.         0.         0.70710678
 0.70710678 0.        ]
State after Hadamard on system C:
[ 0.   0.5  0.5  0.   0.  -0.5 -0.5  0. ]


In [ ]:
m0 = np.kron(np.kron(np.identity(2), np.array([[1,0],[0,0]])), np.identity(2))

In [ ]:
m0 @ state

array([ 0. ,  0.5,  0. ,  0. ,  0. , -0.5,  0. ,  0. ])

In [46]:
m1 = np.kron(np.kron(np.identity(2), np.array([[0,0],[0,1]])), np.identity(2))
m1

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [47]:
m1 @ state

array([ 0. ,  0. ,  0.5,  0. ,  0. ,  0. , -0.5,  0. ])